name: weedy
description: "Simple, lightweight and free diary app to track the progress of your plants."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
