name: growlog
description: "Simple, lightweight and free diary app to track the progress of your plants."
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  path: ^1.9.0
  provider: ^6.1.2
  rxdart: ^0.28.0
  uuid: ^4.4.0
  intl: ^0.19.0
  timeago: ^3.6.1
  image_picker: ^1.1.2
  collection: ^1.15.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  easy_localization: ^3.0.7
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.2
  uri_to_file: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/img/
